### ISSUE TITLE
Not getting past SMS verification screen on Android

### ISSUE THREAD

**Issue by Craques** [argyle-systems/argyle-plugin-react-native#1]
**Environment**
React Native  - 0.61.2
MacOS - 10.14.6
argyle-plugin-react-native - 1.1.2
Android Studio - 3.5
Emulator API - 28

Argyle has been integrated successfully on iOS, however on Android it is not possible to get past the SMS verification step using the sandbox credentials given in the docs, checking logcat I can see the success response but no further progress beyond that `{..., "status":"done","error_code":null,"data_partner":"uber"}`. On iOS the process completes succesfully but on android I get stuck on the screen below.
![Screenshot 2019-11-19 at 20 47 52](https://user-images.githubusercontent.com/11189445/69180908-c9bcc880-0b16-11ea-8c61-3136532e88fe.png)

**Comment by Audrius-Argyle** [comment]
Thanks Charles, we are looking into it.

**Comment by Audrius-Argyle** [comment]
It should now be resolved with the update.

**Comment by Craques** [comment]
Thank you, tried using it, the problem is still there, still getting stuck at the same screen on android

**Comment by gingyle** [comment]
hey @Craques, are you sure you're using the latest version - which is 1.1.3 ?
Just tried and Uber connection worked

**Comment by aanah0** [comment]
Getting the same issue at 1.1.3. Getting stuck at SMS verification screen at Android 

maybe it happens because we are using sandbox apiHost `https://api-sandbox.argyle.io`?

<img width="1435" alt="Screenshot 2019-11-25 at 11 35 11 AM" src="https://user-images.githubusercontent.com/48173606/69529098-45d06980-0f78-11ea-9279-1a3b52431fcb.png">

**Comment by gingyle** [comment]
hey @aanah0 . I'm also testing with sandbox environment (  ArgyleSdk.loginWith("plugin-key", "https://api-sandbox.develop.argyle.io", "")  ). All versions look correct.

Immediately after @Craques' message, I tested with test1@argyle.io account. Are you having issues with this account?

Also, when you go back to the main screen (of all providers), do you see Uber with green checkmark as successfully connected?

**Comment by aanah0** [comment]
hey @gingyle. Thanks for answer

When I use `https://api-sandbox.argyle.io ` like API host - I`m stuck at SMS screen. When I go back - I see that Uber is connected account, and I see the green checkmark 

Now I was trying to use `https://api-sandbox.develop.argyle.io` like API host. But in that case, I see only loading of accounts and they never will be loaded 

maybe API host is the reason for the issue?

**Comment by gingyle** [comment]
@aanah0 @Craques we found another issue that was causing this and already hotfixed that.

already uploaded a 1.1.4 version.
for iOS please do `pod update` command so it's using Argyle framework 1.1.11
Android also need to use Argyle 1.1.11 in the end but that's already packaged in the new RN lib version.
